- array()：将输入数据转换为ndarray，会进行copy。
- asarray()：将输入数据转换为ndarray，如果输入本身是ndarray则不会进行copy。

In [3]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

"""
    array:将输入的数据转换为ndarray，会进行copy
    asarray：将输入的数据转换为ndarray，如果输入本身是ndarray，则不会进行copy
"""
import numpy as np

data = [1,2,3]
print(f"元数据地址为:{id(data)}")
arr = np.array(data)
print(f"arr1地址为:{id(arr)}")
print(f"数组数据为:{arr}")

print("-" * 20)
arr2 = np.array(arr)
print(f"arr2地址为:{id(arr2)}")
print(f"arr2数组数据为:{arr2}")

print("-" * 20)
arr3 = np.asarray(arr)
print(f"arr3地址为:{id(arr3)}")
print(f"arr3数组数据为:{arr3}")

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8
data addr:2190425424192
arr1 addr:2190425390128
arr :[1 2 3]
--------------------
arr2 addr:2190423746640
arr2 :[1 2 3]
--------------------
arr3 addr:2190425390128
arr3 :[1 2 3]


- zeros()：返回给定形状和类型的新数组，用0填充。
- ones()：返回给定形状和类型的新数组，用1填充。
- empty()：返回给定形状和类型的未初始化的新数组。
- zeros_like()：返回与给定数组具有相同形状和类型的0新数组。
- ones_like()：返回与给定数组具有相同形状和类型的1新数组。
- empty_like()：返回与给定数组具有相同形状和类型的未初始化的新数组。


In [7]:
arr1 = np.zeros((2, 5))
print(f"arr1 :{arr1}")
arr2 = np.ones_like(arr1)  # 创建和arr1形状相同的全1数组
print(f"arr2 :{arr2}")
arr3 = np.empty((2, 3))  # 创建未初始化的数组
print(f"arr3 :{arr3}")
arr4 = np.empty_like(arr3)  # 创建和arr3形状相同的未初始化数组
print(f"arr4 :{arr4}")

arr1 :[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
arr2 :[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
arr3 :[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
arr4 :[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


- full()：返回给定形状和类型的新数组，用指定的值填充。
- full_like()：返回与给定数组具有相同形状和类型的用指定值填充的新数组。

In [8]:
arr1 = np.full((2, 3), 6)
print(f"arr1 :{arr1}")

arr2 = np.full_like(arr1, 5)
print(f"arr1 :{arr2}")

arr1 :[[6 6 6]
 [6 6 6]]
arr1 :[[5 5 5]
 [5 5 5]]


- arange()：返回在给定范围内用均匀间隔的值填充的一维数组。

In [9]:
arr1 = np.arange(0, 10, 2)
print(f"arr1 :{arr1}")

arr1 :[0 2 4 6 8]


- linspace()：返回指定范围和元素个数的等差数列。数组元素类型为浮点型。
- logspace()：返回指定指数范围、元素个数、底数的等比数列。

In [10]:
arr1 = np.linspace(start=0, stop=10, num=5)
print(f"arr1 :{arr1}")
arr2 = np.linspace(start=0, stop=10, num=5, endpoint=False)  # 设置endpoint=False，表示不包括stop
print(f"arr2 :{arr2}")
arr3 = np.logspace(start=2, stop=5, num=5, base=2)
print(f"arr3 :{arr3}")

arr1 :[ 0.   2.5  5.   7.5 10. ]
arr2 :[0. 2. 4. 6. 8.]
arr3 :[ 4.          6.72717132 11.3137085  19.02731384 32.        ]


- random.rand()：返回给定形状的数组，用 [0, 1) 上均匀分布的随机样本填充。
- random.randint()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机整数填充。
- random.uniform()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机浮点数填充。
- random.randn()：返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随机样本填充。


In [11]:
arr1 = np.random.rand(2, 3)
print(f"arr1 :{arr1}")
arr2 = np.random.randint(0, 10, (2, 3))
print(f"arr2 :{arr2}")
arr3 = np.random.uniform(3, 6, (2, 3))
print(f"arr3 :{arr3}")
arr4 = np.random.randn(2, 3)
print(f"arr4 :{arr4}")

arr1 :[[0.54160423 0.41792999 0.94631107]
 [0.17081064 0.62914115 0.46328256]]
arr2 :[[3 3 4]
 [6 5 1]]
arr3 :[[3.68679866 3.27053704 5.0959565 ]
 [5.54999622 4.86852978 5.20351847]]
arr4 :[[-0.24896765  0.02778528  0.18473464]
 [ 1.51819192 -1.87225467 -0.1286998 ]]


In [12]:
arr1 = np.matrix("1 2; 3 4")
print(f"arr1 :{arr1}")
arr2 = np.matrix([[1, 2], [3, 4]])
print(f"arr2 :{arr2}")

arr1 :[[1 2]
 [3 4]]
arr2 :[[1 2]
 [3 4]]


In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 使用dtype参数指定元素类型
print(f"arr1 :{arr1}")
arr2 = np.array([0.2, 2.5, 4.8], dtype="i8")
print(f"arr2 :{arr2}")

arr1 :[1. 2. 3.]
arr2 :[0 2 4]


In [15]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(f"arr1 :{arr1}")

arr2 = arr1.astype(np.int64)
print(f"arr2 :{arr2}")

arr1 :[1. 2. 3.]
arr2 :[1 2 3]


In [17]:
arr = np.arange(10)
print(arr)

#获取索引为2的数据
print(arr[2])

# 从索引 2开始到索引9(不包含)停止，间隔为2
print(arr[slice(2,9,2)])

# 从索引2开始到索引9(不包含)停止，间隔为2
print(arr[2:9:2])

# 从索引2开始到最后(不包含)，默认间隔为1
print(arr[2:])

# 从索引2开始到索引9(不包含)结束，默认间隔为1
print(arr[2:9])

[0 1 2 3 4 5 6 7 8 9]
2
[2 4 6 8]
[2 4 6 8]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]


In [18]:
arr1 = np.random.randn(2, 3)
print(arr1)
print(np.abs(arr1))
print(np.ceil(arr1))
print(np.floor(arr1))
print(np.rint(arr1))
print(np.isnan(arr1))
print(np.multiply(arr1, 2))
print(np.divide(arr1, arr1))
print(np.where(arr1 > 0, 1, 0))

[[ 0.23310566 -2.2524755  -0.19329064]
 [ 0.91360976 -0.07449907  0.36256805]]
[[0.23310566 2.2524755  0.19329064]
 [0.91360976 0.07449907 0.36256805]]
[[ 1. -2. -0.]
 [ 1. -0.  1.]]
[[ 0. -3. -1.]
 [ 0. -1.  0.]]
[[ 0. -2. -0.]
 [ 1. -0.  0.]]
[[False False False]
 [False False False]]
[[ 0.46621133 -4.504951   -0.38658128]
 [ 1.82721953 -0.14899813  0.7251361 ]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 0 0]
 [1 0 1]]


In [19]:
arr1 = np.random.randint(1, 5, (2, 3))
print(arr1)
print(np.mean(arr1))
print(np.sum(arr1))
print(np.max(arr1))
print(np.min(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.cumsum(arr1))
print(np.cumprod(arr1))
print(np.cumprod(arr1, axis=1))

[[1 4 4]
 [4 3 1]]
2.8333333333333335
17
4
1
1.3437096247164249
1.8055555555555554
1
0
[ 1  5  9 13 16 17]
[  1   4  16  64 192 192]
[[ 1  4 16]
 [ 4 12 12]]


In [20]:
arr1 = np.array([1, 2, 3, 4, 5])
print(np.any(arr1 > 3))
print(np.all(arr1 > 3))
# ndarray.sort()
arr1 = np.random.randint(0, 10, (3, 3))
print(arr1)
arr1.sort()
print(arr1)
arr1.sort(axis=0)
print(arr1)

True
False
[[2 6 5]
 [2 1 7]
 [4 5 6]]
[[2 5 6]
 [1 2 7]
 [4 5 6]]
[[1 2 6]
 [2 5 6]
 [4 5 7]]


In [21]:
# np.sort()：返回排序后的副本（创建新的数组）。
arr1 = np.random.randint(0, 10, (3, 3))
print(arr1)
print(np.sort(arr1))

[[1 9 5]
 [3 9 1]
 [3 8 1]]
[[1 5 9]
 [1 3 9]
 [1 3 8]]


In [22]:
# np.unique()：计算唯一值并返回有序结果。
arr1 = np.random.randint(0, 5, (3, 3))
print(arr1)
print(np.unique(arr1))

[[0 2 0]
 [1 3 3]
 [2 4 3]]
[0 1 2 3 4]


In [23]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [24]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1 + 100)
print(arr1 - 100)
print(arr1 * 100)
print(arr1 / 100)

[[101 102 103]
 [104 105 106]]
[[-99 -98 -97]
 [-96 -95 -94]]
[[100 200 300]
 [400 500 600]]
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]]


In [25]:
# 	规则1：如果俩个数组的维度数不相同，那么小维度数组的形状将会在最左边补1。
# 一维数组
arr1 = np.array([1, 2, 3])  # 形状为 (3,)
# 二维数组
arr2 = np.array([[4], [5], [6]])  # 形状为 (3, 1)
# 对 arr1 应用规则 1，在其形状最左边补 1，变为 (1, 3)  [[1,2,3]]
# 此时 arr1 形状 (1, 3) 和 arr2 形状 (3, 1) 满足广播条件
result = arr1 + arr2
print("规则 1 示例结果：\n", result)

规则 1 示例结果：
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [26]:
# 	规则2：如果俩个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度大小（元素个数）为1的维度开始扩展 ，（维度必须是1开始）直到所有维度都一样， 以匹配另一个数组的形状。
# 二维数组
arr3 = np.array([[1, 2, 3]])  # 形状为 (1, 3)
# 二维数组
arr4 = np.array([[4], [5], [6]])  # 形状为 (3, 1)

# arr3 沿着第0个维度扩展,将原有的一行数据复制成3行,为 (3, 3)=>[[1,2,3], [1,2,3], [1,2,3]]
# arr4 沿着第1个维度扩展, (3, 3)=>[[4,4,4], [5,5,5], [6,6,6]]
result = arr3 + arr4
print("规则 2 示例结果：\n", result)

规则 2 示例结果：
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [27]:
# 	规则3：如果俩个数组的形状在任何一个维度上都不匹配，并且没有任何一个维度大小等于1，那么会引发异常。
# 一维数组
arr5 = np.array([1, 2, 3])  # 形状为 (3,)
# 一维数组
arr6 = np.array([4, 5])  # 形状为 (2,)
try:
    result = arr5 + arr6
    print(result)
except ValueError as e:
    print(f"规则 3 示例错误信息：{e}")


规则 3 示例错误信息：operands could not be broadcast together with shapes (3,) (2,) 


In [28]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 6 10 12]
 [12 10  6]]
[[ 6 10 12]
 [12 10  6]]


In [29]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5], [4, 3], [2, 1]])
#对于矩阵乘法来说，要求第一个矩阵的列数等于第二个矩阵的行数
print(arr1)
print(arr2)
print(arr1.shape, arr2.shape)
print(np.dot(arr1, arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)
# 一个二维数组跟一个大小合适的一维数组的矩阵点积运算之后将会得到一个一维数组
arr3 = np.array([6, 5, 4])
print(arr1 @ arr3)

[[1 2 3]
 [4 5 6]]
[[6 5]
 [4 3]
 [2 1]]
(2, 3) (3, 2)
[[20 14]
 [56 41]]
[[20 14]
 [56 41]]
[[20 14]
 [56 41]]
[28 73]
